/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Contents of the modprobe.d and udev files for each mode. Pure functions. */
#include "internal.h"

#include <ctype.h>
#include <stdarg.h>
#include <string.h>

#define HEADER "# Generated by GPUShift. Do not edit; run 'gpushift reset' to remove.\n"

struct buf {
	char *p;
	size_t n, len;
	bool overflow;
};

__attribute__((format(printf, 2, 3)))
static void add(struct buf *b, const char *fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	int r = vsnprintf(b->p + b->len, b->n - b->len, fmt, ap);
	va_end(ap);
	if (r < 0 || (size_t)r >= b->n - b->len)
		b->overflow = true;
	else
		b->len += (size_t)r;
}

/* "dddd:bb:dd.f" in hex: the only shape a PCI address can have in udev rules. */
bool gs_valid_pci_address(const char *a)
{
	static const char shape[] = "xxxx:xx:xx.x";
	if (strlen(a) != sizeof(shape) - 1)
		return false;
	for (size_t i = 0; shape[i]; i++)
		if (shape[i] == 'x' ? !isxdigit((unsigned char)a[i]) : a[i] != shape[i])
			return false;
	return true;
}

/* Kernel modules that can drive the dGPU and are not needed by the iGPU. */
static void add_blacklist(struct buf *b, const struct gs_gpu *igpu, const struct gs_gpu *dgpu)
{
	static const char *const nvidia[] = { "nvidia", "nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nouveau", NULL };
	static const char *const amd[] = { "amdgpu", "radeon", NULL };
	static const char *const intel[] = { "i915", "xe", NULL };
	const char *const *mods = dgpu->vendor_id == 0x10de ? nvidia :
				  dgpu->vendor_id == 0x1002 ? amd :
				  dgpu->vendor_id == 0x8086 ? intel : NULL;
	for (size_t i = 0; mods && mods[i]; i++) {
		if (strcmp(mods[i], igpu->driver) == 0)
			continue; /* never blacklist the driver of the GPU that keeps the display */
		add(b, "blacklist %s\nalias %s off\n", mods[i], mods[i]);
	}
}

int gs_config_build(const gs_system *sys, gs_mode mode,
		    char *modprobe, size_t modprobe_len, char *udev, size_t udev_len)
{
	const struct gs_gpu *igpu = gs_igpu(sys), *dgpu = gs_dgpu(sys);
	struct buf m = { modprobe, modprobe_len, 0, false }, u = { udev, udev_len, 0, false };
	if (!igpu || !dgpu || !gs_valid_pci_address(dgpu->address) || !modprobe_len || !udev_len)
		return -1;
	modprobe[0] = udev[0] = '\0';
	bool nvidia = dgpu->vendor_id == 0x10de;
	char slot[16];
	gs_strlcpy(slot, dgpu->address, strlen("dddd:bb:dd") + 1);

	switch (mode) {
	case GS_MODE_INTEGRATED:
		add(&m, HEADER "# Integrated mode: keep the dedicated GPU drivers from loading.\n");
		add_blacklist(&m, igpu, dgpu);
		add(&u, HEADER "# Integrated mode: power down the dedicated GPU (all functions of\n"
			"# its PCI slot) and remove it from the bus.\n"
			"ACTION==\"add\", SUBSYSTEM==\"pci\", KERNEL==\"%s.*\", ATTR{vendor}==\"0x%04x\", "
			"ATTR{power/control}=\"auto\", ATTR{remove}=\"1\"\n", slot, dgpu->vendor_id);
		break;
	case GS_MODE_HYBRID:
		if (!nvidia)
			break; /* other drivers do runtime power management on their own */
		add(&m, HEADER "# Hybrid mode: PRIME render offload with runtime power management.\n"
			"options nvidia-drm modeset=1\n"
			"options nvidia NVreg_DynamicPowerManagement=0x02\n");
		add(&u, HEADER "# Hybrid mode: let the dedicated GPU suspend when idle.\n"
			"ACTION==\"bind\", SUBSYSTEM==\"pci\", KERNEL==\"%s\", ATTR{power/control}=\"auto\"\n"
			"ACTION==\"unbind\", SUBSYSTEM==\"pci\", KERNEL==\"%s\", ATTR{power/control}=\"on\"\n",
			dgpu->address, dgpu->address);
		break;
	case GS_MODE_DEDICATED:
		if (nvidia)
			add(&m, HEADER "# Dedicated mode: kernel modesetting for the display GPU.\n"
				"options nvidia-drm modeset=1\n");
		break;
	default:
		return -1;
	}
	return m.overflow || u.overflow ? -1 : 0;
}
