/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Contents of the modprobe.d and udev files for each mode. Pure functions. */
#include "internal.h"

#include <ctype.h>
#include <dirent.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>

#define HEADER "# Generated by GPUShift. Do not edit; run 'gpushift reset' to remove.\n"

struct buf {
	char *p;
	size_t n, len;
	bool overflow;
};

__attribute__((format(printf, 2, 3)))
static void add(struct buf *b, const char *fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	int r = vsnprintf(b->p + b->len, b->n - b->len, fmt, ap);
	va_end(ap);
	if (r < 0 || (size_t)r >= b->n - b->len)
		b->overflow = true;
	else
		b->len += (size_t)r;
}

/* "dddd:bb:dd.f" in hex: the only shape a PCI address can have in udev rules. */
bool gs_valid_pci_address(const char *a)
{
	static const char shape[] = "xxxx:xx:xx.x";
	if (strlen(a) != sizeof(shape) - 1)
		return false;
	for (size_t i = 0; shape[i]; i++)
		if (shape[i] == 'x' ? !isxdigit((unsigned char)a[i]) : a[i] != shape[i])
			return false;
	return true;
}

static int cmp_str(const void *a, const void *b)
{
	return strcmp(*(char *const *)a, *(char *const *)b);
}

int gs_dgpu_functions(const gs_system *sys, char *buf, size_t n)
{
	const struct gs_gpu *dgpu = gs_dgpu(sys);
	struct buf b = { buf, n, 0, false };
	if (!dgpu || !n)
		return -1;
	buf[0] = '\0';
	if (dgpu->removed) {
		/* Gone from the bus: only what was recorded when it was still there is known. */
		if (sys->state.dgpu_functions[0])
			add(&b, "%s", sys->state.dgpu_functions);
		else
			add(&b, "%s=%04x:%04x", dgpu->address, dgpu->vendor_id, dgpu->device_id);
		return b.overflow ? -1 : 0;
	}
	char path[PATH_MAX], names[8][32];
	char *sorted[8];
	size_t count = 0, slot_len = strlen("dddd:bb:dd");
	DIR *d = gs_rpath(path, sizeof(path), "/sys/bus/pci/devices") == 0 ? opendir(path) : NULL;
	struct dirent *e;
	while (d && (e = readdir(d)) && count < 8)
		if (strncmp(e->d_name, dgpu->address, slot_len) == 0 && gs_valid_pci_address(e->d_name))
			gs_strlcpy(names[count++], e->d_name, sizeof(names[0]));
	if (d)
		closedir(d);
	for (size_t i = 0; i < count; i++)
		sorted[i] = names[i];
	qsort(sorted, count, sizeof(sorted[0]), cmp_str);
	for (size_t i = 0; i < count; i++) {
		unsigned long vendor, device;
		if (gs_rpath(path, sizeof(path), "/sys/bus/pci/devices/%s/vendor", sorted[i]) < 0 ||
		    gs_read_ulong(path, &vendor) < 0 ||
		    gs_rpath(path, sizeof(path), "/sys/bus/pci/devices/%s/device", sorted[i]) < 0 ||
		    gs_read_ulong(path, &device) < 0)
			return -1;
		add(&b, "%s%s=%04lx:%04lx", i ? " " : "", sorted[i], vendor & 0xffff, device & 0xffff);
	}
	return (b.overflow || !count) ? -1 : 0;
}

/* Parses one "addr=vvvv:dddd" token; the state file is input, so it is validated. */
static bool parse_function(const char *tok, char *addr, unsigned *vendor, unsigned *device)
{
	char a[16], v[5], d[5];
	if (strlen(tok) != 22 || tok[12] != '=' || tok[17] != ':')
		return false;
	memcpy(a, tok, 12), a[12] = '\0';
	memcpy(v, tok + 13, 4), v[4] = '\0';
	memcpy(d, tok + 18, 4), d[4] = '\0';
	for (int i = 0; i < 4; i++)
		if (!isxdigit((unsigned char)v[i]) || !isxdigit((unsigned char)d[i]))
			return false;
	if (!gs_valid_pci_address(a))
		return false;
	strcpy(addr, a);
	*vendor = (unsigned)strtoul(v, NULL, 16);
	*device = (unsigned)strtoul(d, NULL, 16);
	return true;
}

/* Kernel modules that can drive the dGPU and are not needed by the iGPU. */
static void add_blacklist(struct buf *b, const struct gs_gpu *igpu, const struct gs_gpu *dgpu)
{
	static const char *const nvidia[] = { "nvidia", "nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nouveau", NULL };
	static const char *const amd[] = { "amdgpu", "radeon", NULL };
	static const char *const intel[] = { "i915", "xe", NULL };
	const char *const *mods = dgpu->vendor_id == 0x10de ? nvidia :
				  dgpu->vendor_id == 0x1002 ? amd :
				  dgpu->vendor_id == 0x8086 ? intel : NULL;
	for (size_t i = 0; mods && mods[i]; i++) {
		if (strcmp(mods[i], igpu->driver) == 0)
			continue; /* never blacklist the driver of the GPU that keeps the display */
		add(b, "blacklist %s\nalias %s off\n", mods[i], mods[i]);
	}
}

int gs_config_build(const gs_system *sys, gs_mode mode,
		    char *modprobe, size_t modprobe_len, char *udev, size_t udev_len)
{
	const struct gs_gpu *igpu = gs_igpu(sys), *dgpu = gs_dgpu(sys);
	struct buf m = { modprobe, modprobe_len, 0, false }, u = { udev, udev_len, 0, false };
	if (!igpu || !dgpu || !gs_valid_pci_address(dgpu->address) || !modprobe_len || !udev_len)
		return -1;
	modprobe[0] = udev[0] = '\0';
	bool nvidia = dgpu->vendor_id == 0x10de;
	char functions[256], addr[16];
	unsigned vendor, device;
	if (gs_dgpu_functions(sys, functions, sizeof(functions)) < 0)
		return -1;

	switch (mode) {
	case GS_MODE_INTEGRATED:
		/*
		 * Same vendor (AMD APU + AMD dGPU, Intel + Intel Arc): its drivers may drive
		 * the iGPU, now or after a kernel update (i915 -> xe), so none is blacklisted
		 * and the exact udev rule alone removes the dGPU.
		 */
		if (igpu->vendor_id != dgpu->vendor_id) {
			add(&m, HEADER "# Integrated mode: keep the dedicated GPU drivers from loading.\n");
			add_blacklist(&m, igpu, dgpu);
		}
		add(&u, HEADER "# Integrated mode: power down every function of the dedicated GPU and\n"
			"# remove it from the bus. Each line matches one exact address and\n"
			"# vendor:device, so a renumbered bus or new hardware never matches.\n");
		for (char *save = NULL, *tok = strtok_r(functions, " ", &save); tok;
		     tok = strtok_r(NULL, " ", &save)) {
			if (!parse_function(tok, addr, &vendor, &device))
				return -1;
			add(&u, "ACTION==\"add\", SUBSYSTEM==\"pci\", KERNEL==\"%s\", ATTR{vendor}==\"0x%04x\", "
				"ATTR{device}==\"0x%04x\", ATTR{power/control}=\"auto\", ATTR{remove}=\"1\"\n",
				addr, vendor, device);
		}
		break;
	case GS_MODE_HYBRID:
		if (!nvidia)
			break; /* other drivers do runtime power management on their own */
		add(&m, HEADER "# Hybrid mode: PRIME render offload with runtime power management.\n"
			"options nvidia-drm modeset=1\n"
			"options nvidia NVreg_DynamicPowerManagement=0x02\n");
		add(&u, HEADER "# Hybrid mode: let the dedicated GPU suspend when idle.\n"
			"ACTION==\"bind\", SUBSYSTEM==\"pci\", KERNEL==\"%s\", ATTR{vendor}==\"0x%04x\", "
			"ATTR{device}==\"0x%04x\", ATTR{power/control}=\"auto\"\n"
			"ACTION==\"unbind\", SUBSYSTEM==\"pci\", KERNEL==\"%s\", ATTR{vendor}==\"0x%04x\", "
			"ATTR{device}==\"0x%04x\", ATTR{power/control}=\"on\"\n",
			dgpu->address, dgpu->vendor_id, dgpu->device_id,
			dgpu->address, dgpu->vendor_id, dgpu->device_id);
		break;
	case GS_MODE_DEDICATED:
		if (nvidia)
			add(&m, HEADER "# Dedicated mode: kernel modesetting for the display GPU.\n"
				"options nvidia-drm modeset=1\n");
		break;
	default:
		return -1;
	}
	return m.overflow || u.overflow ? -1 : 0;
}
